server:
  port: 8080

spring:
  # 数据库
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver # 5.7版本，8版本不能用这个
    url: jdbc:mysql://localhost:3306/myDemo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis-plus:
  configuration:
    # 日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mapper.xml扫描路径
  mapper-locations: classpath:/mapper/**/*.xml