server:
  port: 8080

spring:
  # 项目启动banner图
#  banner:
#    image:
#      location: classpath:/banner/WMDKM.jpg
  # 数据库
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver # 5.7版本，8版本不能用这个
    url: jdbc:mysql://localhost:3306/myDemo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis-plus:
  configuration:
    # 日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 禁用缓存，防止重构项目的时候xml文件不会更新
    cache-enabled: false
    # 开启数据库表结构自动更新
    # default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  # mapper.xml扫描路径
  mapper-locations: classpath:/mapper/**/*.xml
  # 开启别名
  type-aliases-package: com.demo.**.entity

  global-config:
    db-config:
      # 自动映射将表字段的“_”转换为驼峰命名
      column-format: underline_to_camel

# 开启mapper.xml热加载
mybatis-xml-reload:
  enabled: true
  mapper-locations: classpath:/mapper/**/*.xml
